# Generated by Django 5.1.5 on 2025-02-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_timestamp',
            new_name='created_at',
        ),
    ]
